# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: float=None, name: str=None, location: str=None, specialization: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param id: The id of this InlineResponse2001.  # noqa: E501
        :type id: float
        :param name: The name of this InlineResponse2001.  # noqa: E501
        :type name: str
        :param location: The location of this InlineResponse2001.  # noqa: E501
        :type location: str
        :param specialization: The specialization of this InlineResponse2001.  # noqa: E501
        :type specialization: str
        """
        self.swagger_types = {
            'id': float,
            'name': str,
            'location': str,
            'specialization': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'location': 'location',
            'specialization': 'specialization'
        }

        self._id = id
        self._name = name
        self._location = location
        self._specialization = specialization

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> float:
        """Gets the id of this InlineResponse2001.

        dentist id  # noqa: E501

        :return: The id of this InlineResponse2001.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this InlineResponse2001.

        dentist id  # noqa: E501

        :param id: The id of this InlineResponse2001.
        :type id: float
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse2001.

        dentist name  # noqa: E501

        :return: The name of this InlineResponse2001.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse2001.

        dentist name  # noqa: E501

        :param name: The name of this InlineResponse2001.
        :type name: str
        """

        self._name = name

    @property
    def location(self) -> str:
        """Gets the location of this InlineResponse2001.

        workplace location  # noqa: E501

        :return: The location of this InlineResponse2001.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this InlineResponse2001.

        workplace location  # noqa: E501

        :param location: The location of this InlineResponse2001.
        :type location: str
        """

        self._location = location

    @property
    def specialization(self) -> str:
        """Gets the specialization of this InlineResponse2001.

        dentist specialization  # noqa: E501

        :return: The specialization of this InlineResponse2001.
        :rtype: str
        """
        return self._specialization

    @specialization.setter
    def specialization(self, specialization: str):
        """Sets the specialization of this InlineResponse2001.

        dentist specialization  # noqa: E501

        :param specialization: The specialization of this InlineResponse2001.
        :type specialization: str
        """

        self._specialization = specialization
