# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TimeslotTimeslot(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, time: str=None, status: str=None):  # noqa: E501
        """TimeslotTimeslot - a model defined in Swagger

        :param time: The time of this TimeslotTimeslot.  # noqa: E501
        :type time: str
        :param status: The status of this TimeslotTimeslot.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'time': str,
            'status': str
        }

        self.attribute_map = {
            'time': 'time',
            'status': 'status'
        }

        self._time = time
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'TimeslotTimeslot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The timeslot_timeslot of this TimeslotTimeslot.  # noqa: E501
        :rtype: TimeslotTimeslot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> str:
        """Gets the time of this TimeslotTimeslot.

        timeslot  # noqa: E501

        :return: The time of this TimeslotTimeslot.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this TimeslotTimeslot.

        timeslot  # noqa: E501

        :param time: The time of this TimeslotTimeslot.
        :type time: str
        """

        self._time = time

    @property
    def status(self) -> str:
        """Gets the status of this TimeslotTimeslot.

        status  # noqa: E501

        :return: The status of this TimeslotTimeslot.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this TimeslotTimeslot.

        status  # noqa: E501

        :param status: The status of this TimeslotTimeslot.
        :type status: str
        """

        self._status = status
